In [1]:
#Tugas 3 Data Mining
#M. Nur Aziz Musyaffa
#A11.2020.13075

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data1.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)
print(y)

[['Semarang' 46.0 72000.0]
 ['Brebes' 29.0 48000.0]
 ['Bumiayu' 30.0 54000.0]
 ['Bumiayu' 36.0 61000.0]
 ['Bekasi' 40.0 nan]
 ['Brebes' 35.0 nan]
 ['Semarang' nan 52000.0]
 ['Semarang' 43.0 79000.0]
 ['Brebes' 50.0 83000.0]
 ['Bekasi' 40.0 67000.0]
 ['Bekasi' 41.0 nan]
 ['Brebes' 42.0 67000.0]
 ['Semarang' 32.0 67000.0]
 ['Semarang' 45.0 69000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes'
 'Yes']


In [4]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [5]:
print(X)

[['Semarang' 46.0 72000.0]
 ['Brebes' 29.0 48000.0]
 ['Bumiayu' 30.0 54000.0]
 ['Bumiayu' 36.0 61000.0]
 ['Bekasi' 40.0 65363.63636363636]
 ['Brebes' 35.0 65363.63636363636]
 ['Semarang' 39.15384615384615 52000.0]
 ['Semarang' 43.0 79000.0]
 ['Brebes' 50.0 83000.0]
 ['Bekasi' 40.0 67000.0]
 ['Bekasi' 41.0 65363.63636363636]
 ['Brebes' 42.0 67000.0]
 ['Semarang' 32.0 67000.0]
 ['Semarang' 45.0 69000.0]]


In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
print(X)

[[0.0 0.0 0.0 1.0 46.0 72000.0]
 [0.0 1.0 0.0 0.0 29.0 48000.0]
 [0.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 0.0 36.0 61000.0]
 [1.0 0.0 0.0 0.0 40.0 65363.63636363636]
 [0.0 1.0 0.0 0.0 35.0 65363.63636363636]
 [0.0 0.0 0.0 1.0 39.15384615384615 52000.0]
 [0.0 0.0 0.0 1.0 43.0 79000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 40.0 67000.0]
 [1.0 0.0 0.0 0.0 41.0 65363.63636363636]
 [0.0 1.0 0.0 0.0 42.0 67000.0]
 [0.0 0.0 0.0 1.0 32.0 67000.0]
 [0.0 0.0 0.0 1.0 45.0 69000.0]]


In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [9]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 0 1 1]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)
print(X_train)

[[0.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 41.0 65363.63636363636]
 [1.0 0.0 0.0 0.0 40.0 65363.63636363636]
 [0.0 1.0 0.0 0.0 29.0 48000.0]
 [0.0 0.0 0.0 1.0 32.0 67000.0]
 [0.0 0.0 0.0 1.0 46.0 72000.0]
 [0.0 0.0 0.0 1.0 45.0 69000.0]
 [1.0 0.0 0.0 0.0 40.0 67000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 42.0 67000.0]
 [0.0 1.0 0.0 0.0 35.0 65363.63636363636]]


In [11]:
print(X_test)

[[0.0 0.0 1.0 0.0 36.0 61000.0]
 [0.0 0.0 0.0 1.0 43.0 79000.0]
 [0.0 0.0 0.0 1.0 39.15384615384615 52000.0]]


In [12]:
print(y_train)

[0 0 1 1 1 0 1 1 0 0 1]


In [13]:
print(y_test)

[0 1 0]


In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [15]:
print(X_train)

[[0.0 0.0 1.0 -0.6123724356957945 -1.3953639304648695 -1.3714539476339422]
 [1.0 0.0 0.0 -0.6123724356957945 0.2930264253976221 -0.04346156876304767]
 [1.0 0.0 0.0 -0.6123724356957945 0.13953639304648652
  -0.04346156876304767]
 [0.0 1.0 0.0 -0.6123724356957945 -1.548853962816005 -2.072633923677775]
 [0.0 0.0 0.0 1.632993161855452 -1.0883838657625984 0.14776933379436158]
 [0.0 0.0 0.0 1.632993161855452 1.0604765871533002 0.7320859804975554]
 [0.0 0.0 0.0 1.632993161855452 0.9069865548021645 0.3814959924756391]
 [1.0 0.0 0.0 -0.6123724356957945 0.13953639304648652 0.14776933379436158]
 [0.0 1.0 0.0 -0.6123724356957945 1.6744367165578424 2.017582603244582]
 [0.0 1.0 0.0 -0.6123724356957945 0.4465164577487577 0.14776933379436158]
 [0.0 1.0 0.0 -0.6123724356957945 -0.6279137687091915
  -0.04346156876304767]]


In [16]:
print(X_test)

[[0.0 0.0 1.0 -0.6123724356957945 -0.4744237363580559 -0.553410642249471]
 [0.0 0.0 0.0 1.632993161855452 0.6000064900998933 1.5501292858820266]
 [0.0 0.0 0.0 1.632993161855452 0.009660211826294767 -1.6051806063152199]]
